using Microsoft.Azure.Functions.Worker;
using Microsoft.DurableTask;
using Microsoft.Extensions.Logging;
using Kemibrug.AI.Assistant.Models;
using System;
using System.Threading.Tasks;
using Kemibrug.AI.Assistant.TDD_Kickstarter.TDD_Models;

namespace Kemibrug.AI.Assistant
{
    public static class TddKickstarterOrchestrator
    {
        [Function(nameof(TddKickstarterOrchestrator))]
        public static async Task<string> RunOrchestrator(
            [OrchestrationTrigger] TaskOrchestrationContext context)
        {
            var logger = context.CreateReplaySafeLogger(nameof(TddKickstarterOrchestrator));
            var userStoryId = context.GetInput<int>();

            logger.LogInformation("Orchestration started for User Story ID: {userStoryId}", userStoryId);

            try
            {
                // Step 1: Get User Story details
                var userStory = await context.CallActivityAsync<UserStoryInput>(
                    nameof(GetUserStoryActivity), userStoryId);
                logger.LogInformation("Successfully fetched User Story: {title}", userStory.Title);

                // Step 2: Analyze the story
                var analyzedStory = await context.CallActivityAsync<AnalyzedUserStory>(
                    nameof(AnalyzeUserStoryActivity), userStory);

                // Step 3: Generate the test code skeleton
                var generatedCode = await context.CallActivityAsync<string>(
                    nameof(GenerateTestSkeletonActivity), analyzedStory);
                logger.LogInformation("Successfully generated test skeleton for class {className}", analyzedStory.ClassName);

                // Step 4: Upload the generated code as an attachment
                var safeClassName = string.IsNullOrWhiteSpace(analyzedStory?.ClassName)
                    ? $"GeneratedTests_{userStoryId}"
                    : analyzedStory.ClassName;

                var uploadInput = new GeneratedTestUploadInput
                {
                    UserStoryId = userStoryId,
                    FileName = $"{safeClassName}.cs",
                    FileContent = generatedCode,
                    Comment = "This test skeleton was auto-generated by the TDD Kickstarter assistant."
                };

                await context.CallActivityAsync(
                    nameof(UploadGeneratedTestAsAttachmentActivity), uploadInput);

                logger.LogInformation("Orchestration completed successfully for User Story ID: {userStoryId}", userStoryId);
                return "TDD Kickstarter orchestration completed.";
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Orchestration failed for User Story ID {userStoryId}. Error: {message}", userStoryId, ex.Message);

                throw;
            }
        }
    }
}